title: UHF 62
email: hello@uhf62.co.uk
collections:
  policies:
    output: true

defaults:
  - scope:
      path: ""
      type: "policies"
    values:
      layout: "default"


# Build settings
markdown: kramdown
